"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import { GlobalProvider } from '@/contexts/GlobalProvider'
import { LevaStoreProvider } from 'leva'
import { useStoreContext } from 'leva'
import { ModalProvider } from '@/contexts/ModalProvider'
import { TooltipProvider } from '@/components/ui/tooltip'
import { useModal } from '@/contexts/ModalProvider'
import Modal from '@/components/modal/modal-index'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

function RootLayout({ children }: { children: React.ReactNode }) {



  return (
    <html lang="en">
      <body className={""}>{children}</body>
   

    </html>
  );
}

const RootLayoutWithProviders = ({ children }: { children: React.ReactNode }) => {
  const store = useStoreContext();

  return (
    <GlobalProvider>
      <LevaStoreProvider store={store}>
        <ModalProvider>
          <TooltipProvider>
            <RootLayout>{children}</RootLayout>
          </TooltipProvider>
        </ModalProvider>
      </LevaStoreProvider>
    </GlobalProvider>
  );
};

export default RootLayoutWithProviders;